### PR TITLE
ADD: mobile_app update service

### PR DESCRIPTION
**Pull request by koying**
This is a WIP of a service handling sensors updates for the mobile_app component.
Currently, it handles the location update.

Depends on https://github.com/koying/ha_api_client , which is a generated (via Swagger codegen) java wrapper over a swagger definition of the mobile_app api (also WIP)

### CODE REVIEW

**Comment by estevez-dev** [comment]
Hi @koying . It is very nice to see someone helping with HA Client development, but unfortunately mobile_app integration already done in the app in Flutter code. There is registration, updates and notifications already implemented and coming in 0.6.0. The next steps will be to add sensors and location tracking. And we don't need two different mobile_app integration running, one from Java code and second from Flutter.

**Comment by koying** [comment]
Oh, ok, too bad. Will be interesting to see how flutter handles long-running services :)

You might consider committing to github more often, so that potential contributors can see where you're heading ;)

**Comment by estevez-dev** [comment]
I'm committing every day when I'm working on code. There simply was a huge break in my work on this up, but now I'm back. I'll try to write more meaningful commit message in a future.

**Comment by koying** [comment]
NP. So the update code is already on github? Mind pointing me to it?
I only saw the registration code in master ;)

**Comment by estevez-dev** [comment]
Actually updating app registration is in the same function here: https://github.com/estevez-dev/ha_client/blob/de187f3ed5d8a7e8a66bc0dc3016dbddea02c2ab/lib/home_assistant.class.dart#L140
Updating device sensors and location is not implemented yet.

**Comment by koying** [comment]
Oh, yeah, right.
Well, this is a possible implementation of the updating of sensors and location.

The problem you might encounter is that, as of API 26, Android kills background processes (services and receivers) on its own (see the remark on https://developer.android.com/guide/components/services), so flutter must be smart on how to handle updates when the app is not on the foreground.

**Comment by estevez-dev** [comment]
Yeah I know about this problem and there is some workaround. You can schedule some simple code to run on a background. It can solve device location tracking on a background. I hope )

**Comment by Klagio** [comment]
Just wanted to say thanks for this great app. My most used app on my android phone

**Pull request closed without merging**
